apiVersion: v1
kind: Service
metadata:
  name: hello-world-backend-service
spec:
  selector:
    app: hello-world-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
