apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-backend-deployment
  labels:
    app: hello-world-backend
spec:
  selector:
    matchLabels:
      app: hello-world-backend
  template:
    metadata:
      labels:
        app: hello-world-backend
    spec:
      containers:
      - name: hello-world-backend
        image: andreamedia/simple-backend:helloworld2
        ports:
        - containerPort: 8080